#!/usr/bin/env python3
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license
import waggle.plugin
from base64 import b64decode
import zlib
import struct


def process_measurements(message, datagram, sensorgram):
    raw = sensorgram['value']
    hrf = ','.join(map(str, struct.unpack('1024H', zlib.decompress(raw))))

    yield {
        'subsystem': 'nai_detector',
        'sensor': sensorgram['sensor_id'],
        'parameter': sensorgram['parameter_id'],
        'value_raw': 'NA',
        'value_hrf': hrf,
    }


if __name__ == '__main__':
    waggle.plugin.start_processing_measurements(process_measurements)
