from waggle.protocol.v5.decoder import decode_frame

table = {
    'metsense_tmp112': (0x0001, 0x01),
    'metsense_htu21d_temperature': (0x0002, 0x01),
    'metsense_htu21d_humidity': (0x0002, 0x02),
    'metsense_hih4030_humidity': (0x0003, 0x01),
    'metsense_bmp180_temperature': (0x0004, 0x01),
    'metsense_bmp180_pressure': (0x0004, 0x02),
    'metsense_pr103j2_temperature': (0x0005, 0x01),
    'metsense_tsl250rd_light': (0x0006, 0x01),
    'metsense_mma8452q_acc_x': (0x0007, 0x01),
    'metsense_mma8452q_acc_y': (0x0007, 0x02),
    'metsense_mma8452q_acc_z': (0x0007, 0x03),
    'metsense_spv1840lr5h-b': (0x0008, 0x01),
    'metsense_tsys01_temperature': (0x0009, 0x01),
    'lightsense_hmc5883l_hx': (0x000a, 0x01),
    'lightsense_hmc5883l_hz': (0x000a, 0x02),
    'lightsense_hmc5883l_hy': (0x000a, 0x03),
    'lightsense_hih6130_temperature': (0x000b, 0x01),
    'lightsense_hih6130_humidity': (0x000b, 0x02),
    'lightsense_apds_9006_020_light': (0x000c, 0x01),
    'lightsense_tsl260_light': (0x000d, 0x01),
    'lightsense_tsl250_light': (0x000e, 0x01),
    'lightsense_mlx75305': (0x000f, 0x01),
    'lightsense_ml8511': (0x0010, 0x01),
    'lightsense_tmp421': (0x0011, 0x01),
    'chemsense_config': None,
    'chemsense_raw': (0x0110, 0x01),
    'alpha_status': None,
    'rg3_onset_rain': None,
    '5te_soil_dielectric': None,
    '5te_soil_conductivity': None,
    '5te_soil_temperature': None,
    'alpha_histo': None,
    'alpha_serial': None,
    'alpha_firmware': None,
    'alpha_config': None,
    'disabled_sensor': None,
    'pms7003_header': None,
    'pms7003_frame_length': None,
    'pms7003_pm1_cf1': None,
    'pms7003_pm25_cf1': None,
    'pms7003_pm10_cf1': None,
    'pms7003_pm1_atm': None,
    'pms7003_pm25_atm': None,
    'pms7003_pm10_atm': None,
    'pms7003_point_3um_particle': None,
    'pms7003_point_5um_particle': None,
    'pms7003_1um_particle': None,
    'pms7003_2_5um_particle': None,
    'pms7003_5um_particle': None,
    'pms7003_10um_particle': None,
    'pms7003_version': None,
    'pms7003_error_code': None,
    'pms7003_check_sum': None,
    'wagman_id': None,
    'wagman_ver_hw_mj': None,
    'wagman_ver_hw_mi': None,
    'wagman_ver_sw_mj': None,
    'wagman_ver_sw_mi': None,
    'wagman_ver_sw_p': None,
    'wagman_ver_git': None,
    'wagman_time_compile': None,
    'wagman_time_current': None,
    'wagman_boot_flag': None,
    'wagman_uptime': None,
    'wagman_bootloader_nc_flag': None,
    'wagman_boot_count': None,
    'wagman_current_wagman': None,
    'wagman_current_nc': None,
    'wagman_current_ep': None,
    'wagman_current_cs': None,
    'wagman_current_port4': None,
    'wagman_current_port5': None,
    'wagman_temperature_ncheatsink': None,
    'wagman_temperature_epheatsink': None,
    'wagman_temperature_battery': None,
    'wagman_temperature_brainplate': None,
    'wagman_temperature_powersupply': None,
    'wagman_htu21d_temperature': None,
    'wagman_htu21d_humidity': None,
    'wagman_hih4030_humidity': None,
    'wagman_light': None,
    'wagman_failcount_nc': None,
    'wagman_failcount_ep': None,
    'wagman_failcount_cs': None,
    'wagman_failcount_port4': None,
    'wagman_failcount_port5': None,
    'wagman_enabled_nc': None,
    'wagman_enabled_ep': None,
    'wagman_enabled_cs': None,
    'wagman_enabled_port4': None,
    'wagman_enabled_port5': None,
    'wagman_mediaselect_nc': None,
    'wagman_mediaselect_ep': None,
    'wagman_heartbeat_nc': None,
    'wagman_heartbeat_ep': None,
    'wagman_heartbeat_cs': None,
    'wagman_heartbeat_port4': None,
    'wagman_heartbeat_port5': None,
    'wagman_lastboot_nc': None,
    'wagman_lastboot_ep': None,
    'wagman_lastboot_cs': None,
    'wagman_lastboot_port4': None,
    'wagman_lastboot_port5': None,
    'wagman_powerfault_nc': None,
    'wagman_powerfault_ep': None,
    'wagman_powerfault_cs': None,
    'wagman_powerfault_port4': None,
    'wagman_powerfault_port5': None,
    'wagman_bootattempt_nc': None,
    'wagman_bootattempt_ep': None,
    'wagman_bootattempt_cs': None,
    'wagman_bootattempt_port4': None,
    'wagman_bootattempt_port5': None,
    'wagman_rtc': None,
    'nc_machine_id': None,
    'nc_boot_id': None,
    'nc_cpu_temp': None,
    'nc_ram_total': None,
    'nc_ram_free': None,
    'nc_current_disk_type': None,
    'nc_alternate_disk_type': None,
    'nc_partition1_total': None,
    'nc_partition1_used': None,
    'nc_partition2_total': None,
    'nc_partition2_used': None,
    'nc_partition3_total': None,
    'nc_partition3_used': None,
    'nc_current_time': None,
    'nc_uptime': None,
    'nc_idletime': None,
    'nc_load_1': None,
    'nc_load_5': None,
    'nc_load_10': None,
    'nc_ipaddress_octet1': None,
    'nc_ipaddress_octet2': None,
    'nc_ipaddress_octet3': None,
    'nc_ipaddress_octet4': None,
    'nc_hbmode': None,
    'nc_lock_fs': None,
    'nc_lock_pw': None,
    'nc_beehive_ping': None,
    'nc_beehive_sshd': None,
    'nc_local_sshd': None,
    'nc_devices_alphasense': None,
    'nc_devices_metsense': None,
    'nc_devices_modem': None,
    'nc_devices_wagman': None,
    'nc_ver_core_mj': None,
    'nc_ver_core_mi': None,
    'nc_ver_core_p': None,
    'nc_ver_nodecontroller_mj': None,
    'nc_ver_nodecontroller_mi': None,
    'nc_ver_nodecontroller_p': None,
    'nc_ver_plugin_manager_mj': None,
    'nc_ver_plugin_manager_mi': None,
    'nc_ver_plugin_manager_p': None,
    'nc_rabbitmq_queues_data': None,
    'nc_rabbitmq_exchanges_data': None,
    'nc_rabbitmq_shovels_data': None,
    'nc_rabbitmq_shovels_images': None,
    'nc_service_rabbitmq_uptime': None,
    'nc_service_rabbitmq_exitcode': None,
    'nc_service_rabbitmq_state': None,
    'nc_service_rabbitmq_substate': None,
    'nc_service_init_uptime': None,
    'nc_service_init_exitcode': None,
    'nc_service_init_state': None,
    'nc_service_init_substate': None,
    'nc_service_heartbeat_uptime': None,
    'nc_service_heartbeat_exitcode': None,
    'nc_service_heartbeat_state': None,
    'nc_service_heartbeat_substate': None,
    'nc_service_epoch_uptime': None,
    'nc_service_epoch_exitcode': None,
    'nc_service_epoch_state': None,
    'nc_service_epoch_substate': None,
    'nc_service_reversetunnel_uptime': None,
    'nc_service_reversetunnel_exitcode': None,
    'nc_service_reversetunnel_state': None,
    'nc_service_reversetunnel_substate': None,
    'nc_service_wagmandriver_uptime': None,
    'nc_service_wagmandriver_exitcode': None,
    'nc_service_wagmandriver_state': None,
    'nc_service_wagmandriver_substate': None,
    'nc_service_wwan_uptime': None,
    'nc_service_wwan_exitcode': None,
    'nc_service_wwan_state': None,
    'nc_service_wwan_substate': None,
    'ep_machine_id': None,
    'ep_boot_id': None,
    'ep_cpu_temp': None,
    'ep_ram_total': None,
    'ep_ram_free': None,
    'ep_current_disk_type': None,
    'ep_alternate_disk_type': None,
    'ep_partition1_total': None,
    'ep_partition1_used': None,
    'ep_partition2_total': None,
    'ep_partition2_used': None,
    'ep_partition3_total': None,
    'ep_partition3_used': None,
    'ep_current_time': None,
    'ep_uptime': None,
    'ep_idletime': None,
    'ep_load_1': None,
    'ep_load_5': None,
    'ep_load_10': None,
    'ep_ipaddress_octet1': None,
    'ep_ipaddress_octet2': None,
    'ep_ipaddress_octet3': None,
    'ep_ipaddress_octet4': None,
    'ep_hbmode': None,
    'ep_lock_fs': None,
    'ep_lock_pw': None,
    'ep_devices_camera_bottom': None,
    'ep_devices_camera_top': None,
    'ep_devices_microphone': None,
    'ep_ver_core_mj': None,
    'ep_ver_core_mi': None,
    'ep_ver_core_p': None,
    'ep_ver_edge_processor_mj': None,
    'ep_ver_edge_processor_mi': None,
    'ep_ver_edge_processor_p': None,
    'ep_ver_plugin_manager_mj': None,
    'ep_ver_plugin_manager_mi': None,
    'ep_ver_plugin_manager_p': None,
    'ep_rabbitmq_queues_data': None,
    'ep_rabbitmq_queues_images': None,
    'ep_rabbitmq_exchanges_data': None,
    'ep_rabbitmq_exchanges_images': None,
    'ep_service_rabbitmq_uptime': None,
    'ep_service_rabbitmq_exitcode': None,
    'ep_service_rabbitmq_state': None,
    'ep_service_rabbitmq_substate': None,
    'ep_service_init_uptime': None,
    'ep_service_init_exitcode': None,
    'ep_service_init_state': None,
    'ep_service_init_substate': None,
    'ep_service_heartbeat_uptime': None,
    'ep_service_heartbeat_exitcode': None,
    'ep_service_heartbeat_state': None,
    'ep_service_heartbeat_substate': None,
    'net_broadband_rx': None,
    'net_broadband_tx': None,
    'net_lan_rx': None,
    'net_lan_tx': None,
    'net_usb_rx': None,
    'net_usb_tx': None,
    'net_usb_rx': None,
    'net_usb_tx': None,
    'audio_spl_octave1': None,
    'audio_spl_octave2': None,
    'audio_spl_octave3': None,
    'audio_spl_octave4': None,
    'audio_spl_octave5': None,
    'audio_spl_octave6': None,
    'audio_spl_octave7': None,
    'audio_spl_octave8': None,
    'audio_spl_octave9': None,
    'audio_spl_octave10': None,
    'audio_spl_octave_total': None,
    'image_device': None,
    'image_average_color_r': None,
    'image_average_color_g': None,
    'image_average_color_b': None,
    'image_histogram_r': None,
    'image_histogram_g': None,
    'image_histogram_b': None,
    'image_detection_car': None,
    'image_detection_person': None,
    'image_uas_track_name': None,
    'image_uas_last_updated_y': None,
    'image_uas_last_updated_x': None,
    'image_uas_last_updated_speed_x': None,
    'image_uas_last_updated_speed_y': None,
    'image_uas_last_updated_speed_total': None,
    'image_uas_ensemble_cat_number': None,
    'image_uas_ensemble_cat_probability': None,
    'image_uas_box_number': None,
    'image_uas_last_updated_time': None,
    'd3s_content': None,
}


def map_v1_to_v2(datagram_v1):
    decoded_message = decode_frame(datagram_v1)

    for values in decoded_message.values():
        for key, value in values.items():
            try:
                sensor_id, parameter_id = table[key]
            except Exception:
                print('unmatched measurement', key)
                continue

            yield {
                'sensor_id': sensor_id,
                'parameter_id': parameter_id,
                'value': value,
            }
