#!/usr/bin/env python3
import json
import subprocess
import time
import waggle.plugin


plugin = waggle.plugin.Plugin()

while True:
    output = subprocess.check_output([
        'python3',
        '/usr/lib/waggle/core/scripts/status-service',
        '--json',
    ])

    status = json.loads(output.decode())
    print(status, flush=True)

    # plugin.publish_measurements()
    time.sleep(900)
