#!/usr/bin/env python3
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license
import waggle.plugin


subsystem_table = {
    '0000000000000000': 'nc',
    '0000000000000001': 'ep',
}


def normalize_type(x):
    if isinstance(x, bool):
        return int(x)
    if isinstance(x, float):
        return round(x, 3)
    return x

raw_sensors = {
    0xff06, # cu
    0xff08, # vdc
    0xff10, # th
}

def process_measurements(message, datagram, sensorgram):
    value_raw = normalize_type(sensorgram['value'])

    if sensorgram['sensor_id'] not int raw_sensors:
        value_hrf = value_raw
    else:
        value_hrf = 'NA'


    yield {
        'subsystem': subsystem_table[message['sender_sub_id']],
        'sensor': sensorgram['sensor_id'],
        'parameter': sensorgram['parameter_id'],
        'value_raw': value_raw,
        'value_hrf': value_hrf,
    }


if __name__ == '__main__':
    waggle.plugin.start_processing_measurements(process_measurements)
