#!/usr/bin/env python3
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license
import waggle.plugin


subsystem_table = {
    '0000000000000000': 'nc',
    '0000000000000001': 'ep',
}


def normalize_type(x):
    if isinstance(x, bool):
        return int(x)
    if isinstance(x, float):
        return round(x, 3)
    return x


def process_measurements(message, datagram, sensorgram):
    yield {
        'subsystem': subsystem_table[message['sender_sub_id']],
        'sensor': sensorgram['sensor_id'],
        'parameter': sensorgram['parameter_id'],
        'value_raw': 'NA',
        'value_hrf': normalize_type(sensorgram['value']),
    }


if __name__ == '__main__':
    waggle.plugin.start_processing_measurements(process_measurements)
