#!/usr/bin/env python3
import os
import re
import time
from waggle.pipeline import Plugin
from waggle.protocol.v5.encoder import encode_frame

config = [
    # sensor_id, device, name
    (0x90, 'ppp0', 'broadband'),
    (0x91, 'eth0', 'lan'),
    (0x92, 'enx.', 'usb'),
]


def read_file(filename):
    with open(filename) as f:
        return f.read()


def read_device_stats(dev):
    return [
        int(read_file(os.path.join('/sys/class/net', dev, 'statistics/rx_bytes'))),
        int(read_file(os.path.join('/sys/class/net', dev, 'statistics/tx_bytes'))),
    ]


def matching_devices(pattern):
    return sorted([dev for dev in os.listdir('/sys/class/net') if re.match(pattern, dev)])


class SysmonPlugin(Plugin):

    plugin_name = 'sysmon'
    plugin_version = '1'

    def read_values(self):
        print('reading values', flush=True)

        values = {}

        for sensor_id, pattern, name in config:
            try:
                device = matching_devices(pattern)[0]
            except IndexError:
                print('no matching devices for {}'.format(pattern), flush=True)
                continue

            try:
                values[sensor_id] = read_device_stats(device)
                print('{} rx={},tx={}'.format(name, *values[sensor_id]), flush=True)
            except (FileNotFoundError, ValueError):
                print('failed to read {}'.format(name), flush=True)

        return values

    def send_values(self, values):
        if values:
            print('sending values')
            self.send(sensor='', data=encode_frame(values))
        else:
            print('no values to send')

    def run(self):
        while True:
            values = self.read_values()
            self.send_values(values)
            time.sleep(60)


if __name__ == '__main__':
    plugin = SysmonPlugin.defaultConfig()
    plugin.run()
