#!/usr/bin/env python3
import waggle.plugin


def process_measurements(message, datagram, sensorgram):
    yield {
        'subsystem': 'cloud_coverage',
        'sensor': sensorgram['sensor_id'],
        'parameter': sensorgram['parameter_id'],
        'value_raw': 'NA',
        'value_hrf': sensorgram['value'],
    }


if __name__ == '__main__':
    waggle.plugin.start_processing_measurements(process_measurements)

