#!/usr/bin/env python3
import waggle.plugin
import time

credentials = waggle.plugin.Credentials(
    host='beehive1.mcs.anl.gov',
    node_id='0000f00000000001',
    sub_id='0000000000000000',
    cacert='/Users/sean/test/cacert.pem',
    cert='/Users/sean/test/cert.pem',
    key='/Users/sean/test/key.pem')

plugin = waggle.plugin.Plugin(credentials=credentials)

while True:
    plugin.publish_message(
        receiver_id='0000001e0610ba46',
        receiver_sub_id='0000000000000000',
        body=b'testing')

    time.sleep(10)
