#!/usr/bin/env python3
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license
import waggle.plugin
import waggle.protocol
import time
from pprint import pprint

plugin = waggle.plugin.Plugin()

while True:
    for data in plugin.get_waiting_messages():
        message = waggle.protocol.unpack_message(data)
        datagram = waggle.protocol.unpack_datagram(message['body'])

        print('--- recevied message')
        pprint(message)
        pprint(datagram)
        print(flush=True)

    # Add our three measurements to the batch.
    plugin.add_measurement({'sensor_id': 1, 'parameter_id': 0, 'value': 100})

    # Publish the batch.
    plugin.publish_measurements()

    # Wait five seconds before repeating.
    time.sleep(5)
