#!/usr/bin/env python3
import waggle.plugin


# ok...it *is* possible to hack this so that the plugin takes over mapping
def process_measurements(message, datagram, sensorgram):
    yield {
        'subsystem': 'test',
        'sensor': sensorgram['sensor_id'],
        'parameter': sensorgram['parameter_id'],
        'value_raw': sensorgram['value'],
        'value_hrf': sensorgram['value'],
    }


if __name__ == '__main__':
    waggle.plugin.start_processing_measurements(process_measurements)
