#!/usr/bin/env python3
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license
import waggle.plugin
import time


plugin = waggle.plugin.Plugin()

while True:
    plugin.add_measurement({
        'sensor_id': 1,
        'parameter_id': 1,
        'value': 12.3,
    })

    plugin.publish_measurements()

    time.sleep(5)
