#!/usr/bin/env python3
import waggle.plugin
import time


plugin = waggle.plugin.Plugin()

while True:
    for msg in plugin.get_waiting_messages():
        print('Got message:', msg, flush=True)

    plugin.add_measurement({
        'sensor_id': 1,
        'parameter_id': 1,
        'value': 12.3,
    })

    plugin.publish_measurements()

    time.sleep(5)
