#!/usr/bin/env python3
import waggle.plugin
from base64 import b64decode
import zlib
import struct


def process_measurements(message, datagram, sensorgram):
    raw = sensorgram['value']
    hrf = ','.join(map(str, struct.unpack('1024H', zlib.decompress(raw))))

    yield {
        'subsystem': 'nai_detector',
        'sensor': sensorgram['sensor_id'],
        'parameter': sensorgram['parameter_id'],
        'value_raw': raw,
        'value_hrf': hrf,
    }


if __name__ == '__main__':
    waggle.plugin.start_processing_measurements(process_measurements)
