#!/usr/bin/env python3
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license
import waggle.plugin
import time
import struct
import zlib
import sys
from dbaserh.dbaserh import DBASERH
import logging


def compress_spectrum_data(spectrum, time, unit=1024):
    return zlib.compress(struct.pack('1024H', *[int(x) for x in spectrum]))


detector = None
measurement_time = 5

try:
    detector = DBASERH(
        serial=14202220,    # Serial of the device
        hvt=830,            # High voltage in volts (50 - 1200)
        fgn=0.77,           # Find gain (0.5 - 1.2)
        pw=0.75,            # Pulse width (0.75 - 2.0)
        realtime=measurement_time, # Measurement time in seconds
        sleept=0.05)        # Listmode sampling integration time
except Exception:
    logging.exception('Failed to initialize detector')
    sys.exit(1)

try:
    plugin = waggle.plugin.Plugin()

    while True:
        accumulated_data = []
        for idx, measurements in enumerate(detector.histogram()):
            begin_time, channels = measurements
            accumulated_data.extend(channels.tolist())
        print(len(accumulated_data))
        plugin.add_measurement({
            'sensor_id': 2100,
            'parameter_id': 1,
            'value': compress_spectrum_data(channels.tolist(), time=measurement_time),
        })
        plugin.publish_measurements()
        time.sleep(30)
finally:
    detector.end_process()

